apiVersion: v1
kind: Pod
metadata:
  name: iis-aci
  namespace: default
spec:
  containers:
  - name: iis-aci
    image: microsoft/iis:nanoserver
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 1G
        cpu: 1
  nodeName: virtual-kubelet-aci-win